# fly.toml app configuration file generated for ubcdivest-minio on 2024-12-19T18:38:11-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ubcdivest-minio'
primary_region = 'sea'

[build]

[[vm]]
  size = 'shared-cpu-1x'
  memory = 512

[mounts]
source = "miniodata"
destination = "/data"
